<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `quran`
 */

/* `quran`.`quran_sura_list` */
$quran_sura_list = array(
  array('id' => '1','arabic' => 'الفاتحة','english' => 'Al-Fatihah','bangla' => 'আল-ফাতিহা','verses' => '7'),
  array('id' => '2','arabic' => 'البقرة','english' => 'Al-Baqarah','bangla' => 'আল-বাক্বারা','verses' => '286'),
  array('id' => '3','arabic' => 'آل عمران','english' => 'Ali `Imran','bangla' => 'আল-ইমরান','verses' => '200'),
  array('id' => '4','arabic' => 'النساء','english' => 'An-Nisa','bangla' => 'আন-নিসা','verses' => '176'),
  array('id' => '5','arabic' => 'المائدة','english' => 'Al-Ma`idah','bangla' => 'আল-মায়িদাহ','verses' => '120'),
  array('id' => '6','arabic' => 'الأنعام','english' => 'Al-An`am','bangla' => 'আল-আনআম','verses' => '165'),
  array('id' => '7','arabic' => 'الأعراف','english' => 'Al-A`raf','bangla' => 'আল-আরাফ','verses' => '206'),
  array('id' => '8','arabic' => 'الأنفال','english' => 'Al-Anfal','bangla' => 'আল-আনফাল','verses' => '75'),
  array('id' => '9','arabic' => 'التوبة','english' => 'At-Tawbah','bangla' => 'আত-তাওবাহ','verses' => '129'),
  array('id' => '10','arabic' => 'يونس','english' => 'Yunus','bangla' => 'ইউনুস','verses' => '109'),
  array('id' => '11','arabic' => 'هود','english' => 'Hud','bangla' => 'হুদ','verses' => '123'),
  array('id' => '12','arabic' => 'يوسف','english' => 'Yusuf','bangla' => 'ইউসুফ','verses' => '111'),
  array('id' => '13','arabic' => 'الرعد','english' => 'Ar-Ra`d','bangla' => 'আর-রাদ','verses' => '43'),
  array('id' => '14','arabic' => 'ابراهيم','english' => 'Ibrahim','bangla' => 'ইব্রাহিম','verses' => '52'),
  array('id' => '15','arabic' => 'الحجر','english' => 'Al-Hijr','bangla' => 'আল-হিজর','verses' => '99'),
  array('id' => '16','arabic' => 'النحل','english' => 'An-Nahl','bangla' => 'আন-নাহল','verses' => '128'),
  array('id' => '17','arabic' => 'الإسراء','english' => 'Al-Isra','bangla' => 'আল-ইসরা','verses' => '111'),
  array('id' => '18','arabic' => 'الكهف','english' => 'Al-Kahf','bangla' => 'আল-কাহফ','verses' => '110'),
  array('id' => '19','arabic' => 'مريم','english' => 'Maryam','bangla' => 'মারইয়াম','verses' => '98'),
  array('id' => '20','arabic' => 'طه','english' => 'Taha','bangla' => 'ত্বা-হা','verses' => '135'),
  array('id' => '21','arabic' => 'الأنبياء','english' => 'Al-Anbya','bangla' => 'আল-আম্বিয়া','verses' => '112'),
  array('id' => '22','arabic' => 'الحج','english' => 'Al-Hajj','bangla' => 'আল-হাজ্জ','verses' => '78'),
  array('id' => '23','arabic' => 'المؤمنون','english' => 'Al-Mu`minun','bangla' => 'আল-মু`মিনুন','verses' => '118'),
  array('id' => '24','arabic' => 'النور','english' => 'An-Nur','bangla' => 'আন-নূর','verses' => '64'),
  array('id' => '25','arabic' => 'الفرقان','english' => 'Al-Furqan','bangla' => 'আল-ফুরকান','verses' => '77'),
  array('id' => '26','arabic' => 'الشعراء','english' => 'Ash-Shu`ara','bangla' => 'আশ-শু`আরা','verses' => '227'),
  array('id' => '27','arabic' => 'النمل','english' => 'An-Naml','bangla' => 'আন-নামল','verses' => '93'),
  array('id' => '28','arabic' => 'القصص','english' => 'Al-Qasas','bangla' => 'আল-কাসাস','verses' => '88'),
  array('id' => '29','arabic' => 'العنكبوت','english' => 'Al-`Ankabut','bangla' => 'আল-আনকাবুত','verses' => '69'),
  array('id' => '30','arabic' => 'الروم','english' => 'Ar-Rum','bangla' => 'আর-রুম','verses' => '60'),
  array('id' => '31','arabic' => 'لقمان','english' => 'Luqman','bangla' => 'লোকমান','verses' => '34'),
  array('id' => '32','arabic' => 'السجدة','english' => 'As-Sajdah','bangla' => 'আস-সাজদা','verses' => '30'),
  array('id' => '33','arabic' => 'الأحزاب','english' => 'Al-Ahzab','bangla' => 'আল-আহজাব','verses' => '73'),
  array('id' => '34','arabic' => 'سبإ','english' => 'Saba','bangla' => 'সাবা','verses' => '54'),
  array('id' => '35','arabic' => 'فاطر','english' => 'Fatir','bangla' => 'ফাতির','verses' => '45'),
  array('id' => '36','arabic' => 'يس','english' => 'Ya-Sin','bangla' => 'ইয়া-সিন','verses' => '83'),
  array('id' => '37','arabic' => 'الصافات','english' => 'As-Saffat','bangla' => 'আস-সাফফাত','verses' => '182'),
  array('id' => '38','arabic' => 'ص','english' => 'Sad','bangla' => 'ছাদ','verses' => '88'),
  array('id' => '39','arabic' => 'الزمر','english' => 'Az-Zumar','bangla' => 'আয-যুমার','verses' => '75'),
  array('id' => '40','arabic' => 'غافر','english' => 'Ghafir','bangla' => 'গাফির','verses' => '85'),
  array('id' => '41','arabic' => 'فصلت','english' => 'Fussilat','bangla' => 'ফুসসিলাত','verses' => '54'),
  array('id' => '42','arabic' => 'الشورى','english' => 'Ash-Shuraa','bangla' => 'আশ-শুরা','verses' => '53'),
  array('id' => '43','arabic' => 'الزخرف','english' => 'Az-Zukhruf','bangla' => 'আয-যুখরুফ','verses' => '89'),
  array('id' => '44','arabic' => 'الدخان','english' => 'Ad-Dukhan','bangla' => 'আদ-দুখান','verses' => '59'),
  array('id' => '45','arabic' => 'الجاثية','english' => 'Al-Jathiyah','bangla' => 'আল-জাসিয়া','verses' => '37'),
  array('id' => '46','arabic' => 'الأحقاف','english' => 'Al-Ahqaf','bangla' => 'আল-আহকাফ','verses' => '35'),
  array('id' => '47','arabic' => 'محمد','english' => 'Muhammad','bangla' => 'মুহাম্মদ','verses' => '38'),
  array('id' => '48','arabic' => 'الفتح','english' => 'Al-Fath','bangla' => 'আল-ফাতহ','verses' => '29'),
  array('id' => '49','arabic' => 'الحجرات','english' => 'Al-Hujurat','bangla' => 'আল-হুজুরাত','verses' => '18'),
  array('id' => '50','arabic' => 'ق','english' => 'Qaf','bangla' => 'ক্বাফ','verses' => '45'),
  array('id' => '51','arabic' => 'الذاريات','english' => 'Adh-Dhariya','bangla' => 'আয-যারিয়াত','verses' => '60'),
  array('id' => '52','arabic' => 'الطور','english' => 'At-Tur','bangla' => 'আত-তূর','verses' => '49'),
  array('id' => '53','arabic' => 'النجم','english' => 'An-Najm','bangla' => 'আন-নাজম','verses' => '62'),
  array('id' => '54','arabic' => 'القمر','english' => 'Al-Qamar','bangla' => 'আল-ক্বামার','verses' => '55'),
  array('id' => '55','arabic' => 'الرحمن','english' => 'Ar-Rahman','bangla' => 'আর-রহমান','verses' => '78'),
  array('id' => '56','arabic' => 'الواقعة','english' => 'Al-Waqi`ah','bangla' => 'আল-ওয়াকিয়','verses' => '96'),
  array('id' => '57','arabic' => 'الحديد','english' => 'Al-Hadid','bangla' => 'আল-হাদিদ','verses' => '29'),
  array('id' => '58','arabic' => 'المجادلة','english' => 'Al-Mujadila','bangla' => 'আল-মুজাদিলা','verses' => '22'),
  array('id' => '59','arabic' => 'الحشر','english' => 'Al-Hashr','bangla' => 'আল-হাশর','verses' => '24'),
  array('id' => '60','arabic' => 'الممتحنة','english' => 'Al-Mumtahan','bangla' => 'আল-মুমতাহিন','verses' => '13'),
  array('id' => '61','arabic' => 'الصف','english' => 'As-Saf','bangla' => 'আস-সাফ','verses' => '14'),
  array('id' => '62','arabic' => 'الجمعة','english' => 'Al-Jumu`ah','bangla' => 'আল-জুমু`আ','verses' => '11'),
  array('id' => '63','arabic' => 'المنافقون','english' => 'Al-Munafiqu','bangla' => 'আল-মুনাফিকু','verses' => '11'),
  array('id' => '64','arabic' => 'التغابن','english' => 'At-Taghabun','bangla' => 'আত-তাগাবুন','verses' => '18'),
  array('id' => '65','arabic' => 'الطلاق','english' => 'At-Talaq','bangla' => 'আত-তালাক','verses' => '12'),
  array('id' => '66','arabic' => 'التحريم','english' => 'At-Tahrim','bangla' => 'আত-তাহরিম','verses' => '12'),
  array('id' => '67','arabic' => 'الملك','english' => 'Al-Mulk','bangla' => 'আল-মুল্ক','verses' => '30'),
  array('id' => '68','arabic' => 'القلم','english' => 'Al-Qalam','bangla' => 'আল-কলম','verses' => '52'),
  array('id' => '69','arabic' => 'الحاقة','english' => 'Al-Haqqah','bangla' => 'আল-হাক্কাহ','verses' => '52'),
  array('id' => '70','arabic' => 'المعارج','english' => 'Al-Ma`arij','bangla' => 'আল-মাআরিজ','verses' => '44'),
  array('id' => '71','arabic' => 'نوح','english' => 'Nuh','bangla' => 'নুহ','verses' => '28'),
  array('id' => '72','arabic' => 'الجن','english' => 'Al-Jinn','bangla' => 'আল-জিন','verses' => '28'),
  array('id' => '73','arabic' => 'المزمل','english' => 'Al-Muzzammi','bangla' => 'আল-মুজ্জাম্','verses' => '20'),
  array('id' => '74','arabic' => 'المدثر','english' => 'Al-Muddatht','bangla' => 'আল-মুদ্দাসস','verses' => '56'),
  array('id' => '75','arabic' => 'القيامة','english' => 'Al-Qiyamah','bangla' => 'আল-ক্বিয়াম','verses' => '40'),
  array('id' => '76','arabic' => 'الانسان','english' => 'Al-Insan','bangla' => 'আল-ইনসান','verses' => '31'),
  array('id' => '77','arabic' => 'المرسلات','english' => 'Al-Mursalat','bangla' => 'আল-মুরসালাত','verses' => '50'),
  array('id' => '78','arabic' => 'النبإ','english' => 'An-Naba','bangla' => 'আন-নাবা','verses' => '40'),
  array('id' => '79','arabic' => 'النازعات','english' => 'An-Nazi`at','bangla' => 'আন-নাযিআত','verses' => '46'),
  array('id' => '80','arabic' => 'عبس','english' => '`Abasa','bangla' => 'আবাসা','verses' => '42'),
  array('id' => '81','arabic' => 'التكوير','english' => 'At-Takwir','bangla' => 'আত-তাকউইর','verses' => '29'),
  array('id' => '82','arabic' => 'الإنفطار','english' => 'Al-Infitar','bangla' => 'আল-ইনফিতার','verses' => '19'),
  array('id' => '83','arabic' => 'المطففين','english' => 'Al-Mutaffif','bangla' => 'আল-মুতাফফিফ','verses' => '36'),
  array('id' => '84','arabic' => 'الإنشقاق','english' => 'Al-Inshiqaq','bangla' => 'আল-ইনশিকাক','verses' => '25'),
  array('id' => '85','arabic' => 'البروج','english' => 'Al-Buruj','bangla' => 'আল-বুরূজ','verses' => '22'),
  array('id' => '86','arabic' => 'الطارق','english' => 'At-Tariq','bangla' => 'আত-তারিক','verses' => '17'),
  array('id' => '87','arabic' => 'الأعلى','english' => 'Al-A`la','bangla' => 'আল-আ`লা','verses' => '19'),
  array('id' => '88','arabic' => 'الغاشية','english' => 'Al-Ghashiya','bangla' => 'আল-গাশিয়াহ','verses' => '26'),
  array('id' => '89','arabic' => 'الفجر','english' => 'Al-Fajr','bangla' => 'আল-ফজর','verses' => '30'),
  array('id' => '90','arabic' => 'البلد','english' => 'Al-Balad','bangla' => 'আল-বালাদ','verses' => '20'),
  array('id' => '91','arabic' => 'الشمس','english' => 'Ash-Shams','bangla' => 'আশ-শামস','verses' => '15'),
  array('id' => '92','arabic' => 'الليل','english' => 'Al-Layl','bangla' => 'আল-লাইল','verses' => '21'),
  array('id' => '93','arabic' => 'الضحى','english' => 'Ad-Duhaa','bangla' => 'আদ-দুহা','verses' => '11'),
  array('id' => '94','arabic' => 'الشرح','english' => 'Ash-Sharh','bangla' => 'আশ-শারহ','verses' => '8'),
  array('id' => '95','arabic' => 'التين','english' => 'At-Tin','bangla' => 'আত-তিন','verses' => '8'),
  array('id' => '96','arabic' => 'العلق','english' => 'Al-`Alaq','bangla' => 'আল-আলাক','verses' => '19'),
  array('id' => '97','arabic' => 'القدر','english' => 'Al-Qadr','bangla' => 'আল-কদর','verses' => '5'),
  array('id' => '98','arabic' => 'البينة','english' => 'Al-Bayyinah','bangla' => 'আল-баййিনাহ','verses' => '8'),
  array('id' => '99','arabic' => 'الزلزلة','english' => 'Az-Zalzalah','bangla' => 'আয-যালযালাহ','verses' => '8'),
  array('id' => '100','arabic' => 'العاديات','english' => 'Al-`Adiyat','bangla' => 'আল-আদিয়াত','verses' => '11'),
  array('id' => '101','arabic' => 'القارعة','english' => 'Al-Qari`ah','bangla' => 'আল-ক্বারিআহ','verses' => '11'),
  array('id' => '102','arabic' => 'التكاثر','english' => 'At-Takathur','bangla' => 'আত-তাকাসুর','verses' => '8'),
  array('id' => '103','arabic' => 'العصر','english' => 'Al-`Asr','bangla' => 'আল-আসর','verses' => '3'),
  array('id' => '104','arabic' => 'الهمزة','english' => 'Al-Humazah','bangla' => 'আল-হুমাযাহ','verses' => '9'),
  array('id' => '105','arabic' => 'الفيل','english' => 'Al-Fil','bangla' => 'আল-ফিল','verses' => '5'),
  array('id' => '106','arabic' => 'قريش','english' => 'Quraysh','bangla' => 'কুরাইশ','verses' => '4'),
  array('id' => '107','arabic' => 'الماعون','english' => 'Al-Ma`un','bangla' => 'আল-মাউন','verses' => '7'),
  array('id' => '108','arabic' => 'الكوثر','english' => 'Al-Kawthar','bangla' => 'আল-কাওসার','verses' => '3'),
  array('id' => '109','arabic' => 'الكافرون','english' => 'Al-Kafirun','bangla' => 'আল-কাফিরুন','verses' => '6'),
  array('id' => '110','arabic' => 'النصر','english' => 'An-Nasr','bangla' => 'আন-নাসর','verses' => '3'),
  array('id' => '111','arabic' => 'المسد','english' => 'Al-Masad','bangla' => 'আল-মাসাদ','verses' => '5'),
  array('id' => '112','arabic' => 'الإخلاص','english' => 'Al-Ikhlas','bangla' => 'আল-ইখলাস','verses' => '4'),
  array('id' => '113','arabic' => 'الفلق','english' => 'Al-Falaq','bangla' => 'আল-ফালাক','verses' => '5'),
  array('id' => '114','arabic' => 'الناس','english' => 'An-Nas','bangla' => 'আন-নাস','verses' => '6')
);
